### PR TITLE
Communitize must-gather 

### PR DESCRIPTION
**Pull request by masayag**
- Moving gather scripts to collection-scripts resembles the openshift-must-gather structure and somewhat simplify the Dockerfile, where it saves the need to specifically rename the main gather file between source repository to the files on image.
- Change README to refer to 'KubeVirt'
- Omit 'cnv_' from file names

### CODE REVIEW

**Comment by pkliczewski** [comment]
@masayag Looks good, let us know when PR is ready.

**Comment by mmirecki** [comment]
One more step we could take is to remove the _cnv_ part in the script names.
For example gather_cnv_apiservices  -> gather_apiservices.

**Comment by masayag** [comment]
@mmirecki yes, that was the plan right after this script, but I don't see any reason why not to do it right here.

I'll send an update.

**Comment by masayag** [comment]
@mmirecki see output of run on cluster (created by on kubevirtci) - it has few errors regarding node-gather:
https://pastebin.com/dN250LdS

```
error: A server URL must be specified
namespace/node-gather created
serviceaccount/node-gather created
securitycontextconstraints.security.openshift.io/privileged added to: ["system:serviceaccount:node-gather:node-gather"]
daemonset.extensions/node-gather-daemonset created
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
command terminated with exit code 1
Unable to use a TTY - input is not a terminal or the right kind of file
command terminated with exit code 1
```

**Comment by pkliczewski** [comment]
@masayag please rebase

**Pull request merged**
