### PR TITLE
add the missing run permissions to the gather_instancetypes script

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:
```release-note
fix bug: add the missing run permmisions to the gather_instancetypes script
```

### CODE REVIEW

**Comment by machadovilaca** [comment]
maybe in the future we can add a test for this

**Comment by nunnatsa** [comment]
GCP lane passed

/override ci/prow/kubevirt-must-gather-e2e-azure

**Pull request merged**
