### PR TITLE
Add new golang based tool to write vm yamls files from json collection input

### PR DESCRIPTION
**Pull request by nunnatsa**
Fix BZ 2042880 and 2042856

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
Fix BZ 2042880 and 2042856
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
/hold

Should limit the number of goroutins

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
